services:
  postgres:
    image: postgres:16-alpine
    container_name: kametrix-db
    environment:
      POSTGRES_USER: kametrix
      POSTGRES_PASSWORD: kametrix123
      POSTGRES_DB: kametrix
    ports:
      - "5432:5432"
    volumes:
      - kametrix_postgres_data:/var/lib/postgresql/data

volumes:
  kametrix_postgres_data:
